### PR TITLE
Update the README.md file to describe the repo.

### PR DESCRIPTION
**Pull request by SibingWu**
Modify README.md to specify my name in order to practice the use of github

### CODE REVIEW

**Comment by htthach** [comment]
Maybe we can practice putting some description to the PR briefly describing at least:

- What was changed?
- Why was that need to be changed?

So reviewer can get an idea of the goal before looking into the code change?

**Comment by SibingWu** [comment]
> Maybe we can practice putting some description to the PR briefly describing at least:
> 
> * What was changed?
> * Why was that need to be changed?
> 
> So reviewer can get an idea of the goal before looking into the code change?

I update the PR comments:) Thanks for pointing that out!

**Comment by htthach** [comment]
One extra thing to practice. Maybe assign a label on the right side panel?
For this test PR, maybe we can assign an existing "documentation" label.

**Comment by SibingWu** [comment]
> One extra thing to practice. Maybe assign a label on the right side panel?
> For this test PR, maybe we can assign an existing "documentation" label.

Add the label just now:)

**Review by htthach — APPROVED** [review]

**Pull request merged**
